[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "About"
weight = 200
identifier = "about"
url = "/about/"

[[main]]
name = "Love"
weight = 300
identifier = "love"
url = "/love/"

[[main]]
name = "Us"
weight = 400
identifier = "us"
url = "/us/"

[[main]]
name = "Think"
weight = 500
identifier = "think"
url = "/think/"

[[main]]
name = "Observe"
weight = 600
identifier = "observe"
url = "/observe/"

[[main]]
name = "Learn"
weight = 700
identifier = "learn"
url = "/learn/"
